import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AdsConsent } from 'react-native-google-mobile-ads';
import { useApp } from '@/context/AppContext';
import { AppIcon } from '@/components/AppIcon';
import { useTranslation } from '@/hooks/useTranslation';
import { AppLanguage, languageLabels, languages } from '@/constants/i18n';
import { palette } from '@/constants/theme';

export default function SettingsScreen(){
 const {settings,patchSettings,clearHistory,documents}=useApp(); const {t}=useTranslation();
 function wipe(){Alert.alert(t('settings.wipeAlertTitle'),t('settings.wipeAlertMessage',{count:documents.length}),[{text:t('common.cancel'),style:'cancel'},{text:t('common.clear'),style:'destructive',onPress:clearHistory}]);}
 async function privacy(){try{await AdsConsent.gatherConsent();Alert.alert(t('settings.consentUpdatedTitle'),t('settings.consentUpdatedMessage'));}catch{Alert.alert(t('settings.consentErrorTitle'),t('settings.consentErrorMessage'));}}
 return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.content}><View><Text style={styles.kicker}>{t('settings.kicker')}</Text><Text style={styles.title}>{t('settings.title')}</Text><Text style={styles.sub}>{t('settings.subtitle')}</Text></View>
  <Section title={t('settings.languageSection')}><View style={styles.segment}>{languages.map((code)=><LanguageChip key={code} code={code} active={settings.language===code} onPress={()=>patchSettings({language:code})}/>)}</View></Section>
  <Section title={t('settings.readingSection')}><SettingRow icon="rotate" title={t('settings.horizontalTitle')} desc={t('settings.horizontalDesc')} value={settings.horizontal} onValueChange={v=>patchSettings({horizontal:v})}/><SettingRow icon="snap" title={t('settings.snapTitle')} desc={t('settings.snapDesc')} value={settings.pagingEnabled} onValueChange={v=>patchSettings({pagingEnabled:v})}/><SettingRow icon="moon" title={t('settings.nightTitle')} desc={t('settings.nightDesc')} value={settings.invertPdfPages} onValueChange={v=>patchSettings({invertPdfPages:v})}/></Section>
  <Section title={t('settings.adsSection')}><Pressable onPress={privacy} style={styles.actionRow}><View style={styles.actionIcon}><AppIcon name="shield" color={palette.emerald}/></View><View style={{flex:1}}><Text style={styles.actionTitle}>{t('settings.consentTitle')}</Text><Text style={styles.actionDesc}>{t('settings.consentDesc')}</Text></View><AppIcon name="chevronRight" size={17} color="#64748B"/></Pressable></Section>
  <Section title={t('settings.dataSection')}><Pressable onPress={wipe} style={styles.actionRow}><View style={[styles.actionIcon,{backgroundColor:'rgba(248,113,113,.08)'}]}><AppIcon name="trash" color={palette.danger}/></View><View style={{flex:1}}><Text style={[styles.actionTitle,{color:'#FCA5A5'}]}>{t('settings.wipeTitle')}</Text><Text style={styles.actionDesc}>{t('settings.wipeDesc')}</Text></View></Pressable></Section>
  <View style={styles.about}><AppIcon name="info" size={18} color="#64748B"/><Text style={styles.aboutText}>{t('settings.about')}</Text></View>
 </ScrollView></SafeAreaView>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={{gap:9}}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.sectionBox}>{children}</View></View>}
function LanguageChip({code,active,onPress}:{code:AppLanguage;active:boolean;onPress:()=>void}){return <Pressable onPress={onPress} accessibilityRole="button" accessibilityState={{selected:active}} style={[styles.segmentItem,active&&styles.segmentActive]}>{active?<AppIcon name="check" size={15} color="#fff"/>:null}<Text style={[styles.segmentText,active&&{color:'#fff'}]}>{languageLabels[code]}</Text></Pressable>}
function SettingRow({icon,title,desc,value,onValueChange}:{icon:React.ComponentProps<typeof AppIcon>['name'];title:string;desc:string;value:boolean;onValueChange:(next:boolean)=>void}){return <View style={styles.settingRow}><View style={styles.actionIcon}><AppIcon name={icon} size={19} color="#8792FF"/></View><View style={{flex:1}}><Text style={styles.actionTitle}>{title}</Text><Text style={styles.actionDesc}>{desc}</Text></View><Switch value={value} onValueChange={onValueChange} trackColor={{false:'#283249',true:'#5865E8'}} thumbColor="#F8FAFC"/></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:palette.ink},content:{padding:18,gap:22,paddingBottom:32},kicker:{color:'#6E7BEE',fontSize:9,fontWeight:'900',letterSpacing:1.8},title:{color:palette.white,fontSize:25,fontWeight:'900',marginTop:4},sub:{color:palette.muted,fontSize:12,marginTop:6},sectionTitle:{color:'#66738A',fontSize:9,fontWeight:'900',letterSpacing:1.5,marginLeft:3},sectionBox:{borderRadius:18,backgroundColor:'#11192B',borderWidth:1,borderColor:palette.line,overflow:'hidden'},segment:{flexDirection:'row',padding:7,gap:6},segmentItem:{flex:1,height:48,borderRadius:12,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:6},segmentActive:{backgroundColor:'#5662E6'},segmentText:{color:'#738098',fontSize:11,fontWeight:'800'},settingRow:{minHeight:72,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:11,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:palette.line},actionRow:{minHeight:76,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:11},actionIcon:{width:40,height:40,borderRadius:12,backgroundColor:'rgba(91,103,241,.1)',alignItems:'center',justifyContent:'center'},actionTitle:{color:'#E5E7EB',fontSize:13,fontWeight:'800'},actionDesc:{color:'#6F7D95',fontSize:10.5,marginTop:4},about:{flexDirection:'row',justifyContent:'center',alignItems:'center',gap:7},aboutText:{color:'#536078',fontSize:10.5}});
