import React from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AdsConsent } from 'react-native-google-mobile-ads';
import { useApp } from '@/context/AppContext';
import { AppIcon } from '@/components/AppIcon';
import { palette } from '@/constants/theme';

export default function SettingsScreen(){
 const {settings,patchSettings,clearHistory,documents}=useApp();
 function wipe(){Alert.alert('Kütüphaneyi temizle',`${documents.length} belge ve okuma geçmişi uygulamadan silinecek.`,[{text:'Vazgeç',style:'cancel'},{text:'Temizle',style:'destructive',onPress:clearHistory}]);}
 async function privacy(){try{await AdsConsent.gatherConsent();Alert.alert('Reklam izinleri güncellendi','Google reklam izin durumu yeniden kontrol edildi.');}catch{Alert.alert('Gizlilik seçenekleri','AdMob izin akışı şu anda kullanılamıyor. AdMob > Privacy & messaging ayarlarını kontrol edin.');}}
 return <SafeAreaView style={styles.safe} edges={['top']}><ScrollView contentContainerStyle={styles.content}><View><Text style={styles.kicker}>AYARLAR</Text><Text style={styles.title}>Senin okuma alanın</Text><Text style={styles.sub}>Okuma davranışını ve gizlilik seçeneklerini yönet.</Text></View>
  <Section title="VARSAYILAN OKUMA"><SettingRow icon="rotate" title="Yatay okuma" desc="Sayfaları sağa-sola kaydır" value={settings.horizontal} onValueChange={v=>patchSettings({horizontal:v})}/><SettingRow icon="snap" title="Sayfaya yapış" desc="Her kaydırmada tek sayfaya otur" value={settings.pagingEnabled} onValueChange={v=>patchSettings({pagingEnabled:v})}/><SettingRow icon="moon" title="PDF gece modu" desc="Sayfa renklerini ters çevir" value={settings.invertPdfPages} onValueChange={v=>patchSettings({invertPdfPages:v})}/></Section>
  <Section title="REKLAM & GİZLİLİK"><Pressable onPress={privacy} style={styles.actionRow}><View style={styles.actionIcon}><AppIcon name="shield" color={palette.emerald}/></View><View style={{flex:1}}><Text style={styles.actionTitle}>Reklam izinlerini yenile</Text><Text style={styles.actionDesc}>Google UMP izin durumunu yeniden kontrol et</Text></View><AppIcon name="chevronRight" size={17} color="#64748B"/></Pressable></Section>
  <Section title="VERİ"><Pressable onPress={wipe} style={styles.actionRow}><View style={[styles.actionIcon,{backgroundColor:'rgba(248,113,113,.08)'}]}><AppIcon name="trash" color={palette.danger}/></View><View style={{flex:1}}><Text style={[styles.actionTitle,{color:'#FCA5A5'}]}>Kütüphaneyi temizle</Text><Text style={styles.actionDesc}>Yerel PDF kopyalarını ve geçmişi sil</Text></View></Pressable></Section>
  <View style={styles.about}><AppIcon name="info" size={18} color="#64748B"/><Text style={styles.aboutText}>PDF Okuyucu • Expo SDK 57 • Yerel PDF işleme</Text></View>
 </ScrollView></SafeAreaView>;
}
function Section({title,children}:{title:string;children:React.ReactNode}){return <View style={{gap:9}}><Text style={styles.sectionTitle}>{title}</Text><View style={styles.sectionBox}>{children}</View></View>}
function SettingRow({icon,title,desc,value,onValueChange}:any){return <View style={styles.settingRow}><View style={styles.actionIcon}><AppIcon name={icon} size={19} color="#8792FF"/></View><View style={{flex:1}}><Text style={styles.actionTitle}>{title}</Text><Text style={styles.actionDesc}>{desc}</Text></View><Switch value={value} onValueChange={onValueChange} trackColor={{false:'#283249',true:'#5865E8'}} thumbColor="#F8FAFC"/></View>}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:palette.ink},content:{padding:18,gap:22,paddingBottom:32},kicker:{color:'#6E7BEE',fontSize:9,fontWeight:'900',letterSpacing:1.8},title:{color:palette.white,fontSize:25,fontWeight:'900',marginTop:4},sub:{color:palette.muted,fontSize:12,marginTop:6},sectionTitle:{color:'#66738A',fontSize:9,fontWeight:'900',letterSpacing:1.5,marginLeft:3},sectionBox:{borderRadius:18,backgroundColor:'#11192B',borderWidth:1,borderColor:palette.line,overflow:'hidden'},segment:{flexDirection:'row',padding:7,gap:6},segmentItem:{flex:1,height:48,borderRadius:12,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:6},segmentActive:{backgroundColor:'#5662E6'},segmentText:{color:'#738098',fontSize:11,fontWeight:'800'},settingRow:{minHeight:72,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:11,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:palette.line},actionRow:{minHeight:76,flexDirection:'row',alignItems:'center',paddingHorizontal:13,gap:11},actionIcon:{width:40,height:40,borderRadius:12,backgroundColor:'rgba(91,103,241,.1)',alignItems:'center',justifyContent:'center'},actionTitle:{color:'#E5E7EB',fontSize:13,fontWeight:'800'},actionDesc:{color:'#6F7D95',fontSize:10.5,marginTop:4},about:{flexDirection:'row',justifyContent:'center',alignItems:'center',gap:7},aboutText:{color:'#536078',fontSize:10.5}});
