import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Alert, AppState, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { PdfView } from '@kishannareshpal/expo-pdf';
import * as Sharing from 'expo-sharing';
import { useApp } from '@/context/AppContext';
import { AppIcon } from '@/components/AppIcon';
import { AdBanner } from '@/components/AdBanner';
import { useTranslation } from '@/hooks/useTranslation';
import { palette } from '@/constants/theme';

export default function ReaderScreen(){
 const {id}=useLocalSearchParams<{id:string}>();
 const {getDocument,touchDocument,updateProgress,toggleFavorite,settings,patchSettings}=useApp(); const {t,locale}=useTranslation();
 const formatNumber=useCallback((value:number)=>new Intl.NumberFormat(locale).format(value),[locale]);
 const doc=getDocument(id);
 const [page,setPage]=useState(1); const [count,setCount]=useState(doc?.pageCount||0);
 const [password,setPassword]=useState(''); const [passwordDraft,setPasswordDraft]=useState(''); const [passwordOpen,setPasswordOpen]=useState(false); const [error,setError]=useState('');
 const [locked,setLocked]=useState(false); const [passwordError,setPasswordError]=useState('');
 const savedPage=useState(()=>doc?.lastPage??1)[0]; const [hintVisible,setHintVisible]=useState((doc?.lastPage??1)>1);
 const pendingProgress=useRef<{page:number;pageCount?:number}|null>(null); const progressTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const flushProgress=useCallback(()=>{if(progressTimer.current)clearTimeout(progressTimer.current);progressTimer.current=null;const pending=pendingProgress.current;pendingProgress.current=null;if(id&&pending)updateProgress(id,pending.page,pending.pageCount)},[id,updateProgress]);
 const queueProgress=useCallback((nextPage:number,nextPageCount?:number)=>{pendingProgress.current={page:nextPage,pageCount:nextPageCount};if(progressTimer.current)clearTimeout(progressTimer.current);progressTimer.current=setTimeout(flushProgress,750)},[flushProgress]);
 useEffect(()=>{if(id)touchDocument(id)},[id,touchDocument]);
 useEffect(()=>{const subscription=AppState.addEventListener('change',(state)=>{if(state==='inactive'||state==='background')flushProgress()});return()=>subscription.remove()},[flushProgress]);
 useEffect(()=>()=>flushProgress(),[flushProgress]);
 if(!doc) return <SafeAreaView style={styles.center}><AppIcon name="file" size={42} color="#475569"/><Text style={styles.errorTitle}>{t('reader.notFound')}</Text><Pressable onPress={()=>router.back()} style={styles.backButton}><Text style={styles.backText}>{t('reader.goBack')}</Text></Pressable></SafeAreaView>;
 async function share(){if(!doc)return;try{if(!await Sharing.isAvailableAsync())throw new Error('sharing_unavailable');await Sharing.shareAsync(doc.uri,{mimeType:'application/pdf',dialogTitle:doc.name})}catch{Alert.alert(t('reader.shareFailedTitle'),t('reader.shareFailedMessage'))}}
 return <View style={styles.root}>
   <SafeAreaView edges={['top']} style={styles.top}><Pressable onPress={()=>router.back()} accessibilityRole="button" accessibilityLabel={t('a11y.goBack')} style={styles.iconButton}><AppIcon name="back"/></Pressable><View style={{flex:1,minWidth:0}}><Text numberOfLines={1} style={styles.title}>{doc.name}</Text><Text style={styles.subtitle}>{count?t('reader.pageOf',{page:formatNumber(page),total:formatNumber(count)}):t('reader.loading')}</Text></View><Pressable onPress={()=>toggleFavorite(doc.id)} accessibilityRole="button" accessibilityLabel={doc.isFavorite?t('a11y.removeFromFavorites'):t('a11y.addToFavorites')} style={styles.iconButton}><AppIcon name="heart" color={doc.isFavorite?palette.rose:'#CBD5E1'}/></Pressable><Pressable onPress={share} accessibilityRole="button" accessibilityLabel={t('a11y.share')} style={styles.iconButton}><AppIcon name="share" color="#CBD5E1"/></Pressable></SafeAreaView>
   <View style={styles.viewer}>
    {error?<View style={styles.center}><AppIcon name="info" size={36} color={palette.danger}/><Text style={styles.errorTitle}>{t('reader.failedTitle')}</Text><Text style={styles.errorText}>{error}</Text><Pressable onPress={()=>setError('')} style={styles.backButton}><Text style={styles.backText}>{t('reader.retry')}</Text></Pressable></View>:
    locked?<View style={styles.center}><AppIcon name="shield" size={40} color={palette.pdfRedSoft}/><Text style={styles.errorTitle}>{t('reader.lockedTitle')}</Text><Text style={styles.errorText}>{t('reader.lockedText')}</Text><Pressable onPress={()=>setPasswordOpen(true)} accessibilityRole="button" accessibilityLabel={t('reader.enterPassword')} style={styles.backButton}><Text style={styles.backText}>{t('reader.enterPassword')}</Text></Pressable></View>:
    <><PdfView key={password} style={{flex:1}} uri={doc.uri} password={password||undefined} horizontal={settings.horizontal} pagingEnabled={settings.pagingEnabled} doubleTapToZoom pageGap={10} contentPadding={{top:10,bottom:10,left:8,right:8}} fitMode="width" pageColorInverted={settings.invertPdfPages} autoScale
      onLoadComplete={({pageCount})=>{setCount(pageCount);if(id&&doc.pageCount!==pageCount)updateProgress(id,doc.lastPage,pageCount)}}
      onPageChanged={({pageIndex,pageCount})=>{const p=pageIndex+1;setPage(p);setCount(pageCount);queueProgress(p,pageCount);if(hintVisible)setHintVisible(false)}}
      onError={({code,message})=>{if(code==='password_required'||code==='password_incorrect'){setLocked(true);setPasswordOpen(true);setPasswordError(code==='password_incorrect'?t('reader.passwordIncorrect'):'')}else setError(message||t('reader.genericError'))}}/>
      {hintVisible?<View pointerEvents="none" style={styles.hintWrap}><View style={styles.hint}><AppIcon name="clock" size={14} color={palette.ink}/><Text style={styles.hintText}>{t('reader.lastPageHint',{page:savedPage})}</Text></View></View>:null}</>}
   </View>
   <AdBanner separateFromNavigation/>
   <SafeAreaView edges={['bottom']} style={styles.toolbarSafe}><View style={styles.toolbar}><ReaderToggle icon="rotate" active={settings.horizontal} label={settings.horizontal?t('reader.horizontal'):t('reader.vertical')} onPress={()=>patchSettings({horizontal:!settings.horizontal})}/><ReaderToggle icon="snap" active={settings.pagingEnabled} label={settings.pagingEnabled?t('reader.singlePage'):t('reader.flow')} onPress={()=>patchSettings({pagingEnabled:!settings.pagingEnabled})}/><View style={styles.pageChip}><Text style={styles.pageStrong}>{formatNumber(page)}</Text><Text style={styles.pageMuted}> / {count?formatNumber(count):'—'}</Text></View><ReaderToggle icon="moon" active={settings.invertPdfPages} label={t('reader.night')} onPress={()=>patchSettings({invertPdfPages:!settings.invertPdfPages})}/></View></SafeAreaView>
   <Modal visible={passwordOpen} transparent animationType="fade" onRequestClose={()=>setPasswordOpen(false)}><View style={styles.modalBg}><View style={styles.modalCard}><Text style={styles.modalTitle}>{t('reader.passwordTitle')}</Text><Text style={styles.modalText}>{t('reader.passwordText')}</Text>{passwordError?<Text style={styles.passwordErrorText}>{passwordError}</Text>:null}<TextInput secureTextEntry value={passwordDraft} onChangeText={setPasswordDraft} placeholder={t('reader.passwordPlaceholder')} placeholderTextColor="#64748B" style={styles.passwordInput}/><Pressable onPress={()=>{if(!passwordDraft)return;setPassword(passwordDraft);setPasswordOpen(false);setLocked(false);setError('');setPasswordError('')}} style={styles.unlock}><Text style={styles.unlockText}>{t('reader.passwordUnlock')}</Text></Pressable><Pressable onPress={()=>{setPasswordOpen(false);setPasswordDraft('')}} style={styles.passwordCancel}><Text style={styles.passwordCancelText}>{t('common.cancel')}</Text></Pressable></View></View></Modal>
 </View>;
}
type ReaderToggleProps={icon:React.ComponentProps<typeof AppIcon>['name'];active:boolean;label:string;onPress:()=>void};
function ReaderToggle({icon,active,label,onPress}:ReaderToggleProps){return <Pressable onPress={onPress} style={[styles.tool,active&&styles.toolActive]}><AppIcon name={icon} size={18} color={active?'#fff':palette.steel}/><Text style={[styles.toolText,active&&{color:'#fff'}]}>{label}</Text></Pressable>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:palette.ink},top:{minHeight:68,backgroundColor:palette.ink,flexDirection:'row',alignItems:'center',paddingHorizontal:10,gap:6,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:palette.line},iconButton:{width:40,height:40,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:'rgba(255,255,255,.035)'},title:{color:palette.white,fontSize:13.5,fontWeight:'800'},subtitle:{color:palette.muted,fontSize:10.5,marginTop:3},viewer:{flex:1,backgroundColor:'#151719'},toolbarSafe:{backgroundColor:palette.ink},toolbar:{height:61,backgroundColor:palette.ink,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:palette.line,flexDirection:'row',alignItems:'center',justifyContent:'space-around',paddingHorizontal:6},tool:{minWidth:57,height:45,borderRadius:12,alignItems:'center',justifyContent:'center',gap:3},toolActive:{backgroundColor:palette.redGlow},toolText:{color:palette.muted,fontSize:8.5,fontWeight:'700'},pageChip:{height:34,minWidth:67,borderRadius:12,backgroundColor:palette.metal,alignItems:'center',justifyContent:'center',flexDirection:'row',paddingHorizontal:10},pageStrong:{color:palette.white,fontSize:12,fontWeight:'900'},pageMuted:{color:palette.muted,fontSize:10},center:{flex:1,backgroundColor:palette.ink,alignItems:'center',justifyContent:'center',padding:28},errorTitle:{color:palette.white,fontSize:17,fontWeight:'800',marginTop:14},errorText:{color:palette.muted,fontSize:12,textAlign:'center',lineHeight:18,marginTop:7},backButton:{backgroundColor:palette.pdfRed,paddingHorizontal:18,paddingVertical:11,borderRadius:12,marginTop:16},backText:{color:'#fff',fontSize:12,fontWeight:'800'},modalBg:{flex:1,backgroundColor:'rgba(2,3,4,.84)',justifyContent:'center',padding:22},modalCard:{backgroundColor:palette.metal,borderRadius:22,borderWidth:1,borderColor:palette.line,padding:20},modalTitle:{color:palette.white,fontSize:19,fontWeight:'900'},modalText:{color:palette.muted,fontSize:12,marginTop:6},passwordInput:{height:49,borderRadius:13,backgroundColor:palette.ink,borderWidth:1,borderColor:palette.line,color:'#fff',paddingHorizontal:13,marginTop:16},unlock:{height:48,borderRadius:13,backgroundColor:palette.pdfRed,alignItems:'center',justifyContent:'center',marginTop:11},unlockText:{color:'#fff',fontWeight:'800',fontSize:13},passwordCancel:{height:42,alignItems:'center',justifyContent:'center',marginTop:4},passwordCancelText:{color:palette.muted,fontWeight:'800',fontSize:12},passwordErrorText:{color:palette.danger,fontSize:12,marginTop:8},hintWrap:{position:'absolute',top:12,left:0,right:0,alignItems:'center'},hint:{flexDirection:'row',alignItems:'center',gap:6,backgroundColor:'#F0F1F3',paddingHorizontal:12,paddingVertical:7,borderRadius:20},hintText:{color:palette.ink,fontSize:11.5,fontWeight:'800'}});
